### ISSUE TITLE
Realtime API send always 0 capacity

### ISSUE THREAD

**Issue by andreazanetti92** [sugo-code/docs#1]
Realtime API on HEROKU send always 0 capacity even if on Silo Dashboard capacity have some capacity indicator marked.

**Comment by nicolabovolato** [comment]
I think this issue belongs to the data api, capacity readings from sensors are sent as is to the message bus. Capacity thresholds are set on a scalar value while capacity sensor reading are fractions. The data api does not consider that and when a fractioned value exceeds a scalar threshold it sends a _parameter:threshold-reached_ to the message bus.
